<?php

namespace App\Http\Requests;

use App\Models\User;
use Illuminate\Foundation\Http\FormRequest;

class AuthenticatedRequest extends FormRequest
{
    public function authorize()
    {
        return parent::user() != null;
    }

    public function rules()
    {
        return [];
    }

    public function user($guard = null): User
    {
        return parent::user($guard); // TODO: Change the autogenerated stub
    }
}
